name: skill_wallet_kool
description: 3-screen starter for Skill Wallet Kool
publish_to: 'none'
version: 1.0.0+2
environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  google_fonts: ^6.1.0
  shared_preferences: ^2.2.2
  provider: ^6.0.5
  flutter_inappwebview: ^6.0.0
  record: ^6.1.2
  path_provider: ^2.1.1
  #youtube_player_flutter: ^9.1.2
  youtube_player_iframe: ^5.2.2
  # video_player: ^2.10.0
  media_kit: ^1.2.1
  media_kit_video: ^1.3.1
  media_kit_libs_video: ^1.0.7 
  audioplayers: ^6.5.1
  file_picker: ^10.3.3
  url_launcher: ^6.3.2
  flutter_dotenv: ^6.0.0
  image_picker: ^1.2.1
  flutter_localizations:
    sdk: flutter
  intl: any
  # flutter_facebook_auth: 7.1.5

  # flutter_secure_storage: ^9.0.0

  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # uni_links: ^0.5.1
  app_links: ^6.4.1
  webview_flutter: ^4.4.2
  supabase_flutter: ^2.12.0
  google_sign_in: ^7.2.0
  share_plus: ^10.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  test: any
  flutter_launcher_icons: "^0.14.4"

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon.jpg"
  min_sdk_android: 32 

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/SWK_home.png
    - assets/images/Analysis_img.jpg
    - assets/icons/
    - .env
