name: skill_wallet_kool
description: 3-screen starter for Skill Wallet Kool
publish_to: 'none'
version: 0.0.1+1
environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  google_fonts: ^6.1.0
  shared_preferences: ^2.2.2
  provider: ^6.0.5
  flutter_inappwebview: ^6.0.0
  record: ^6.1.2
  path_provider: ^2.1.1
  #youtube_player_flutter: ^9.1.2
  youtube_player_iframe: ^5.2.2
  # video_player: ^2.10.0
  media_kit: ^1.2.1
  media_kit_video: ^1.3.1
  media_kit_libs_video: ^1.0.7 
  audioplayers: ^6.5.1
  image_picker: ^1.2.0
  file_picker: ^10.3.3
  url_launcher: ^6.3.2
  flutter_dotenv: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  test: any

flutter:
  uses-material-design: true
  assets:
    - assets/images/SWK_home.png
    - .env
